name: Python

on:
  push:
  pull_request:
    branches:
      - master

# Cancel previous CI runs when new commits are added to a PR.
concurrency:
  group: ${{ github.head_ref || github.run_id }}-python
  cancel-in-progress: true

jobs:
  build:
    # NOTE: runner strategy is to split across os and python version, but test multiple
    # sphinx versions on a single runner.  So do not add a matrix.sphinx-version.
    name: ${{ matrix.os }} / ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.7', '3.8', '3.9', '3.10']
    steps:
      - uses: actions/checkout@v4
      ##################################################################################
      - name: Install Doxygen (macOS)
        if: contains(matrix.os, 'macos')
        run: |
          HOMEBREW_NO_AUTO_UPDATE=1 brew install doxygen
      - name: Install Doxygen (Ubuntu)
        if: contains(matrix.os, 'ubuntu')
        run: |
          sudo apt-get install -y doxygen
      - name: Install Doxygen (Windows)
        if: contains(matrix.os, 'windows')
        run: |
          # This command has been failing with source forge mirror issues
          # choco install doxygen.install --version 1.9.6
          #
          # https://github.com/actions/runner-images/issues/92#issuecomment-1172456433
          $url = "https://www.doxygen.nl/files/doxygen-1.9.6.windows.x64.bin.zip"
          Start-DownloadWithRetry -Url $url -Name "doxygen.zip" -DownloadPath "C:\"
          Extract-7Zip -Path  "C:\doxygen.zip" -DestinationPath "C:\Program Files\doxygen"
          # Extracts to C:\Program Files\doxygen
          #   - doxygen.exe
          #   - doxyindexer.exe
          #   - doxysearch.cgi.exe
          #   - doxywizard.exe
          #   - libclang.dll
          echo "C:\Program Files\doxygen" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      ##################################################################################
      - name: Doxygen Version Dump
        run: doxygen --version
      ##################################################################################
      - name: Use Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install Python Tools
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox tox-gh-actions
          python -m pip install codecov coverage
      # Sphinx #####################################################################
      - name: Test Python ${{ matrix.python-version }}
        run: |
          tox -- --cov-report xml:coverage.xml --cov
